dist: trusty
language: node_js
node_js:
  - "8"

script:
  - npm run clean && npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  keep-history: true
  repo: valor-software/valor-software.github.io
  target-branch: master
  on:
    branch: ci-autodeploy-path-swap

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  keep-history: true
  repo: VS-work/VS-work.github.io
  target-branch: master
  on:
    branch: test-travis-autodeploy
