dist: trusty
language: node_js
node_js:
  - "8"

script:
  - npm run clean && npm run build

if: branch = ci-autodeploy-path-swap
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  keep-history: true
  target-branch: master
  repo: valor-software/valor-software.github.io

if: branch = test-travis-autodeploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  keep-history: true
  repo: VS-work/VS-work.github.io
  target-branch: master
