language: node_js
node_js:
  - "6"

#before_install: npm i -g npm@latest

script:
  - npm test

after_success:
  - ./node_modules/.bin/codecov  -f coverage/coverage-final.json
  - npm run flow.clean
  - npm run flow.build:prod
  - openssl aes-256-cbc -K $encrypted_3fc7c455333c_key -iv $encrypted_3fc7c455333c_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - ./node_modules/.bin/gh-pages -d dist -r git@github.com:VS-work/VS-work.github.io.git -b master"

addons:
  # sauce labs tunel connector (read more https://docs.travis-ci.com/user/sauce-connect/ )
  sauce_connect: true
  firefox: "42.0"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    # required by node-gyp to build some packages
    packages:
    - g++-4.8

